---
grails:
  profile: vue
  codegen:
    defaultPackage: eu.devexpert.madhouse
  gorm:
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
server:
  port: 8181
info:
  app:
    name: "@info.app.name@"
    version: "@info.app.version@"
    grailsVersion: "@info.app.grailsVersion@"
spring:
  jmx:
    unique-names: true
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false
  devtools:
    restart:
      additional-exclude:
        - "*.gsp"
        - "**/*.gsp"
        - "*.gson"
        - "**/*.gson"
        - "logback.groovy"
        - "*.properties"
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: "/actuator"
      path-mapping.health: healthcheck
  endpoint:
    info:
      enabled: true
    health:
      show-details: when_authorized

---
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      json:
        - application/json
        - text/json
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: "*/*"
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8
---
grails:
  cors:
    enabled: true

quartz.jdbcStore: true
quartz:
  pluginEnabled: true
  autoStartup: true
  purgeQuartzTablesOnStartup: false
  threadPool:
    class: "org.quartz.simpl.SimpleThreadPool"
    threadCount: 25
    threadPriority: 5
  jobStore:
    class: "org.quartz.impl.jdbcjobstore.JobStoreTX"
    driverDelegateClass: "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
    useProperties: false
    dataSource: "production"
    tablePrefix: "qrtz_"
  dataSource:
    development:
      driver: "org.postgresql.Driver"
      URL: "jdbc:postgresql://localhost:5432/madhouse_02_20"
      user: "madhouse"
      password: "madhouse"
      maxConnections: 5
    production:
      driver: "org.postgresql.Driver"
      URL: "jdbc:postgresql://madhousev2-db:5432/madhouse"
      user: "madhouse"
      password: "madhouse"
      maxConnections: 5
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password: ""

environments:
  development:
    dataSource:
      dbCreate: update
      url: jdbc:postgresql://localhost:5432/madhouse_02_20
      username: "madhouse"
      password: "madhouse"
      driverClassName: "org.postgresql.Driver"
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
      logSql: false
      formatSql: false
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
    logging:
      jul:
        usebridge: true
    plugin:
      springsecurity:
        debug:
          useFilter: true
  production:
    dataSource:
      dbCreate: update
      url: jdbc:postgresql://madhousev2-db:5432/madhouse
      username: "madhouse"
      password: "madhouse"
      driverClassName: "org.postgresql.Driver"
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
      logSql: false
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
    logging:
      jul:
        usebridge: true
    plugin:
      springsecurity:
        debug:
          useFilter: true
graphql:
  enabled: true
  graphiql:
    enabled: true
    path: /graphiql
    template-path: classpath:graphiql/index.html
    template-parameters:
    page-title: GraphiQL
