schema: schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: http://localhost:8181/graphql
      headers:
        user-agent: JS GraphQL
        Origin: http://localhost:10002
        Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwcmluY2lwYWwiOiJINHNJQUFBQUFBQUFBSlZTUDA4VVFSUlwvdDl6bERDUUlKcGhZUUFOMFpNOW9lUlVnR3NseUdNOXJJTUhNN2I1YkIyWm4xcGxadUd2SVZWcFFZRlFTRXI4QzMwUWJQNENCZ3BhYWxqZDd3SjQwaE9uMnpXOVwvXC85NmNYRURGYUhnWmE4YUY4Vk9SeFZ6Nkp0VmN4Z2JEVEhQYjh6T0RPa0tiSTk3a3dCWk5ZSEJLSHBRQzhIaGs0VW13elhaWlRUQVoxOWJiMnhqYWVsZkRDNlhqYThhT1pnbnVLYjNqMzNLSFN1TlwvQWdXMTk5eUQ2Z1pNc2pCVW1iUU5KVmU2S2RjWWJjQkVNUXRVdU9OR1V5SGRvTFNjQ1RNTXJhSmtiWUZSQUdNc3M1OFVxWEkwRmg0UHpHYVdpMW9UYlQyQVJ5a3podHpkU2RLMHpycTdkellsSmZnTSsxRHVwaVU2MU4yOGdcL3FPeDE5V1FsQnFycVNaYThsRVJiekRuVGp4OTZlXC9cL3ozODFXOTVBTlRKd3YzXC9GUE5uUzlEXC92WFU1a3hkZENpMDhIYkpld09yZGxOeE1Gc3dmTkRybGY4ZnZmaHhkZk4wY0lXV0hlUDN3ZmN3dFhqZlhXMVpKeWpTemFtaEhSTHRYZGkrQnlKZnVKN1wvWlFzOXY4aVFWU0M5S1dveHVKUXBpaWx2V1N0ejBiV0gwXC9YcXc4bkh4MWRyYmh2dXNzQ2poa2xUSDg5QnVXMzZnYUZjSDU5XC8rSE02ZUVzTXFWSGFaeUpBNm55aEFqU3hwb1wvNXljalE5OXZQc0lFOHdVSzEycmdEeEJcL3A3RVFNQUFBPT0iLCJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoibXloYWIiLCJleHAiOjE3MDMwODc3NDYsImlhdCI6MTY4NTA4Nzc0Nn0.Z5MD-D0K3ASQtIU6q7rLCkygLeBjPjRSi8__A3nP7Uc
      introspect: true
